language: generic
dist: xenial
sudo: required

services:
- docker

before_install:
- if test -n "$ca" ; then sudo apt-get install -y libnss3-tools ; fi

install: true

before_script:
- TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE:-$TRAVIS_COMMIT~..$TRAVIS_COMMIT} && echo "$TRAVIS_COMMIT_RANGE"
- export TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE/.../..} && echo "$TRAVIS_COMMIT_RANGE"
- export FILES_CHANGED=$( git diff --name-only $TRAVIS_COMMIT_RANGE | sort ) && echo "$FILES_CHANGED"
- export TRAVIS_DOCKERFILES=$( sed 's/^ *env. dockerfile=/Dockerfile./;s/ .*//;/^Dockerfile/p;d' .travis.yml | sort ) && echo "$TRAVIS_DOCKERFILES"
- export BUILD_DOCKERFILES=$( grep '^Dockerfile\.' <( echo "$FILES_CHANGED" ) ) ; echo "$BUILD_DOCKERFILES"
- export NONDOCKERFILES_CHANGED=$( grep -v '^Dockerfile\.' <( echo "$FILES_CHANGED" ) ) ; echo "$NONDOCKERFILES_CHANGED"
- if test -z "$FILES_CHANGED" || test -n "$NONDOCKERFILES_CHANGED" ; then export BUILD_DOCKERFILES=$TRAVIS_DOCKERFILES ; fi ; echo "$BUILD_DOCKERFILES"
- if grep -F "Dockerfile.$dockerfile" <( echo "$BUILD_DOCKERFILES" ) ; then export RUN_DOCKER_BUILD=1 ; fi
- perl -e 'print map "$_=$ENV{$_}".chr(10), sort keys %ENV'

stages:
- sanity
- build

matrix:
  include:
    - stage: sanity
      script: if comm -23 <( echo "$FILES_CHANGED" ) <( echo "$TRAVIS_DOCKERFILES" ) | grep Dockerfile. ; then echo "Dockerfile modified but not tracked by Travis." >&2 ; exit 1 ; else echo "No unexpected Dockerfile changes, OK." ; fi
    - stage: build
      env: dockerfile=fedora-31 readonly=--read-only
    - stage: build
      env: dockerfile=fedora-31 ca=--external-ca readonly=--read-only
    - stage: build
      env: dockerfile=fedora-31
    - stage: build
      env: dockerfile=fedora-30
    - stage: build
      env: dockerfile=fedora-29
    - stage: build
      env: dockerfile=centos-8 readonly=--read-only
    - stage: build
      env: dockerfile=centos-8 ca=--external-ca readonly=--read-only
    - stage: build
      env: dockerfile=centos-8
    - stage: build
      env: dockerfile=centos-7
    - stage: build
      env: dockerfile=fedora-rawhide
    - stage: build
      env: dockerfile=fedora-23 replica=none seccomp=unconfined readonly=--read-only
  exclude:
    - stage: build
      env: dockerfile=rhel-7
    - stage: build
      env: dockerfile=rhel-8
    - stage: build
      env: dockerfile=fedora-28
    - stage: build
      env: dockerfile=fedora-27
    - stage: build
      env: dockerfile=fedora-26 replica=none
    - stage: build
      env: dockerfile=fedora-25 seccomp=unconfined
    - stage: build
      env: dockerfile=fedora-24 replica=none seccomp=unconfined

script:
- if test -n "$RUN_DOCKER_BUILD" ; then docker build -t local/freeipa-server -f Dockerfile.$dockerfile . ; fi
- if test -n "$RUN_DOCKER_BUILD" ; then tests/run-master-and-replica.sh local/freeipa-server ; fi

after_failure:
- docker ps -aq | while read i ; do docker rm -f $i ; done
- if test -n "$RUN_DOCKER_BUILD" ; then tests/run-partial-tests.sh Dockerfile.$dockerfile ; fi
