language: minimal
os: linux
dist: focal

virt: vm
arch: arm64-graviton2
group: edge

services:
- docker

install:
- if test -n "$ca" ; then sudo apt-get install -y libnss3-tools ; fi
- export docker=${docker:-docker}
- if test "$docker" == "sudo podman" -o "$docker" == 'podman' ; then . /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman ; fi
- if [ "$docker" = 'podman' ] ; then sudo apt-get install -y fuse-overlayfs uidmap slirp4netns ; fi

before_script:
- perl -e 'print map "$_=$ENV{$_}".chr(10), sort keys %ENV'

script:
- $docker load -i local-freeipa-server-$dockerfile.tar
- $docker run --rm --entrypoint rpm local/freeipa-server:$dockerfile -qa | sort
- tests/run-master-and-replica.sh local/freeipa-server:$dockerfile

after_failure:
- $docker ps -aq | while read i ; do $docker rm -f $i ; done
- tests/run-partial-tests.sh Dockerfile.$dockerfile

stages:
- build
- test

jobs:
  include:
    - &build-stage
      stage: build
      env: dockerfile=fedora-33
      install: export docker=${docker:-docker}
      script: $docker build -t local/freeipa-server:$dockerfile -f Dockerfile.$dockerfile . && $docker save --output local-freeipa-server-$dockerfile.tar local/freeipa-server:$dockerfile
      after_failure: skip
      workspaces:
        create:
          name: fedora-33
          paths:
            - local-freeipa-server-$dockerfile.tar

    - stage: test
      env: dockerfile=fedora-33 readonly=--read-only replica=none
      workspaces:
        use: fedora-33
    - env: dockerfile=fedora-33 docker='sudo podman' replica=none
      workspaces:
        use: fedora-33
    - env: dockerfile=fedora-33 docker=podman replica=none
      workspaces:
        use: fedora-33

    - &test-k3s
      env: dockerfile=fedora-33
      install: skip
      after_failure: skip
      script: tests/run-master-in-k3s.sh local/freeipa-server:$dockerfile local-freeipa-server-$dockerfile.tar
      workspaces:
        use: fedora-33

