language: generic

sudo: required

services:
- docker

before_install:
- sudo apt-get install -y libnss3-tools

install: true

before_script:
- TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE:-$TRAVIS_COMMIT~..$TRAVIS_COMMIT} && echo "$TRAVIS_COMMIT_RANGE"
- export TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE/.../..} && echo "$TRAVIS_COMMIT_RANGE"
- export FILES_CHANGED=$( git diff --name-only $TRAVIS_COMMIT_RANGE | sort ) && echo "$FILES_CHANGED"
- export TRAVIS_DOCKERFILES=$( sed 's/^ *env. dockerfile=/Dockerfile./;s/ .*//;/^Dockerfile/p;d' .travis.yml | sort ) && echo "$TRAVIS_DOCKERFILES"
- export BUILD_DOCKERFILES=$( grep '^Dockerfile\.' <( echo "$FILES_CHANGED" ) ) ; echo "$BUILD_DOCKERFILES"
- export NONDOCKERFILES_CHANGED=$( grep -v '^Dockerfile\.' <( echo "$FILES_CHANGED" ) ) ; echo "$NONDOCKERFILES_CHANGED"
- if test -z "$FILES_CHANGED" || test -n "$NONDOCKERFILES_CHANGED" ; then export BUILD_DOCKERFILES=$TRAVIS_DOCKERFILES ; fi ; echo "$BUILD_DOCKERFILES"
- env | sort

stages:
- sanity
- build

matrix:
  include:
    - stage: sanity
      script: if comm -23 <( echo "$FILES_CHANGED" ) <( echo "$TRAVIS_DOCKERFILES" ) | grep Dockerfile. ; then echo "Dockerfile modified but not tracked by Travis." >&2 ; exit 1 ; else echo "No unexpected Dockerfile changes, OK." ; fi
    - stage: build
      env: dockerfile=fedora-28 privileged=--privileged
    - stage: build
      env: dockerfile=fedora-28 ca=--external-ca privileged=--privileged
    - stage: build
      env: dockerfile=fedora-27 privileged=--privileged
    - stage: build
      env: dockerfile=centos-7
    - stage: build
      env: dockerfile=centos-7 ca=--external-ca
  exclude:
    - stage: build
      env: dockerfile=fedora-rawhide
    - stage: build
      env: dockerfile=fedora-26 privileged=--privileged
    - stage: build
      env: dockerfile=fedora-25
    - stage: build
      env: dockerfile=fedora-24
    - stage: build
      env: dockerfile=fedora-23
    - stage: build
      env: dockerfile=rhel-7

script:
- tests/build-and-run.sh
