version: 2.1

commands:
  configure-docker:
    steps:
      - run: sudo systemctl disable --now docker.service docker.socket
      - run: sudo apt update
      - run: sudo apt install -y uidmap
      - run: |
          cat \<<EOT | sudo tee /etc/apparmor.d/home.circleci.bin.rootlesskit
          # ref: https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
          abi <abi/4.0>,
          include <tunables/global>
          /home/circleci/bin/rootlesskit flags=(unconfined) {
            userns,
            # Site-specific additions and overrides. See local/README for details.
            include if exists <local/home.circleci.bin.rootlesskit>
          }
          EOT
      - run: sudo systemctl restart apparmor.service
      - run: curl -fsSL https://get.docker.com/rootless | FORCE_ROOTLESS_INSTALL=1 sh
      - run: docker info --format '{{ .ClientInfo.Context }}' | grep rootless
  install-podman:
    steps:
      - run: sudo apt update
      - run: sudo apt install -y podman
      - run: echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$( id -u )/bus" >> ~/.circlerc

jobs:
  build-and-run-container:
    machine:
      image: ubuntu-2404:edge
    resource_class: arm.medium
    parameters:
      os:
        type: string
      docker:
        type: string
        default: docker
    environment:
      readonly: --read-only
    steps:
      - checkout
      - when:
          condition:
            equal: [ << parameters.docker >>, docker ]
          steps:
            - configure-docker
      - when:
          condition:
            equal: [ << parameters.docker >>, podman ]
          steps:
            - install-podman
      - run: << parameters.docker >> build -t localhost/freeipa-server:<< parameters.os >> -f Dockerfile.<< parameters.os >> .
      - run: docker="<< parameters.docker >>" tests/run-master-and-replica.sh localhost/freeipa-server:<< parameters.os >>

workflows:
  test-freeipa-container:
    jobs:
      - build-and-run-container:
          name: "FreeIPA AlmaLinux 10 on docker"
          os: almalinux-10
      - build-and-run-container:
          name: "FreeIPA Rocky Linux 9 on podman"
          os: rocky-9
          docker: podman
